"""
TestDiagnosticoGenerator — Plugin for the test_diagnostico report type.

Input: 'analisis de datos.xlsx' manually placed at data/test_diagnostico/analysis/
Output: PDFs generated by PDFGenerator (one per student, handling both Egresado and
        Cuarto medio student types internally).

PRECONDITION: The input Excel file must be manually prepared and placed at
data/test_diagnostico/analysis/analisis de datos.xlsx before running this plugin.
"""
import logging
from pathlib import Path
from reports.base import BaseReportGenerator
from reports.test_diagnostico.pdf_generator import PDFGenerator

logger = logging.getLogger(__name__)

SEGMENTOS_PATH = "templates/test_diagnostico/Segmentos.xlsx"
TEMPLATE_PATH = "templates/test_diagnostico/plantilla_plan_de_estudio.html"


class TestDiagnosticoGenerator(BaseReportGenerator):
    def __init__(self):
        super().__init__("test_diagnostico")

    def download(self) -> str:
        """Return path to Excel input file; fail fast if missing."""
        excel_path = self.analysis_dir / "analisis de datos.xlsx"
        if not excel_path.exists():
            raise FileNotFoundError(
                f"[test_diagnostico] Required input file not found: {excel_path}\n"
                "Manually prepare 'analisis de datos.xlsx' and copy it to the expected path before running.\n"
                f"Expected path: {excel_path.resolve()}"
            )
        logger.info(f"[test_diagnostico] Input file found: {excel_path}")
        return str(excel_path)

    def analyze(self, download_result: str) -> str:
        # No analysis step — data is pre-analyzed in the Excel workbook
        return download_result

    def render(self, analysis_result: str) -> Path:
        output_dir = self.data_dir / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
        generator = PDFGenerator(
            analysis_excel_path=analysis_result,
            segmentos_excel_path=SEGMENTOS_PATH,
            html_template_path=TEMPLATE_PATH,
        )
        logger.info(f"[test_diagnostico] Starting PDF generation for all students")
        generator.generate_all_reports()
        logger.info(f"[test_diagnostico] PDF generation complete")
        return output_dir
